# Generated by Django 5.0.2 on 2025-04-06 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('properties', '0002_property_area_property_created_at_and_more'),
        ('tenants', '0002_remove_tenant_monthly_rent_tenant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='متأخر؟'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='نهاية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='بداية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر'),
        ),
    ]
