# Generated by Django 5.0.2 on 2025-04-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_property_created_at_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='monthly_rent',
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(default=1, max_length=20, verbose_name='الرقم المدني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='commercial_license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_end_date',
            field=models.DateField(verbose_name='نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_start_date',
            field=models.DateField(verbose_name='بداية العقد'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rent_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='العقار المستأجر'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
