# Generated by Django 5.0.2 on 2025-04-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_unit'),
        ('tenants', '0002_remove_tenant_monthly_rent_tenant_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرين'},
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='lease_end_date',
            new_name='contract_end',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='lease_start_date',
            new_name='contract_start',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='commercial_license',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rent_property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='الاسم الكامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الهوية/السجل التجاري'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ساري', 'ساري'), ('منتهي', 'منتهي'), ('ملغي', 'ملغي')], default='ساري', max_length=10, verbose_name='حالة العقد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('فرد', 'فرد'), ('شركة', 'شركة')], default=0, max_length=10, verbose_name='نوع المستأجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='properties.unit', verbose_name='الوحدة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
