# Generated by Django 5.0.3 on 2025-04-07 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرين'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='tenants/contracts/', verbose_name='نسخة من عقد الإيجار'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/id_docs/', verbose_name='صورة البطاقة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contract_end',
            field=models.DateField(verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contract_start',
            field=models.DateField(verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
    ]
