# Generated by Django 5.0.2 on 2025-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل'), ('warehouse', 'مخزن'), ('parking', 'موقف')], max_length=50)),
                ('owner_share', models.DecimalField(decimal_places=2, help_text='نسبة المالك', max_digits=5)),
                ('investor_share', models.DecimalField(decimal_places=2, help_text='نسبة المستثمر', max_digits=5)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
