# Generated by Django 5.0.2 on 2025-04-06 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='المساحة (م2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الاإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='investor_share',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة المستثمر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_share',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة المالك'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل'), ('warehouse', 'مخزن'), ('parking', 'موقف سيارات')], max_length=20, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الإيجار الشهري'),
        ),
    ]
