# Generated by Django 5.0.2 on 2025-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_property_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='investor_share',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_share',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_price',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='المدينة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/', verbose_name='مخطط الطوابق'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='صورة العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_apartments',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_offices',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المكاتب'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_parkings',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المواقف'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_shops',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المحلات'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_stores',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المخازن'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('سكني', 'سكني'), ('تجاري', 'تجاري'), ('سكني تجاري', 'سكني تجاري'), ('مبني إداري', 'مبني إداري')], default=0, max_length=50, verbose_name='نوع العقار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف التفصيلي'),
        ),
    ]
