# Generated by Django 5.0.2 on 2025-04-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_area_remove_property_floor_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('عمارة', 'عمارة'), ('برج', 'برج'), ('مركز تجاري', 'مركز تجاري'), ('فيلا', 'فيلا'), ('سكن موظفين', 'سكن موظفين')], default='', max_length=50, verbose_name='الفئة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='يوجد مصعد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='يوجد موقف'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('مشغول', 'مشغول'), ('شاغر', 'شاغر')], default='شاغر', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='صورة')),
                ('caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='تعليق')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
        ),
    ]
