# Generated by Django 5.0.3 on 2025-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_category_property_has_elevator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'صورة عقار', 'verbose_name_plural': 'صور العقارات'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_apartments',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_offices',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_parkings',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_shops',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_stores',
        ),
        migrations.AddField(
            model_name='property',
            name='floor_count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الطوابق'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الوحدات'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرى تعديل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('عمارة', 'عمارة'), ('برج', 'برج'), ('مركز تجاري', 'مركز تجاري'), ('فيلا', 'فيلا'), ('سكن موظفين', 'سكن موظفين'), ('محلات', 'محلات'), ('مخزن', 'مخزن'), ('مكتب', 'مكتب')], max_length=50, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('سكني', 'سكني'), ('تجاري', 'تجاري'), ('سكني تجاري', 'سكني تجاري')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
