# Generated by Django 5.0.2 on 2025-04-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
            ],
            options={
                'verbose_name': 'فئة عقار',
                'verbose_name_plural': 'فئات العقارات',
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='unit_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type',
        ),
        migrations.AddField(
            model_name='property',
            name='governorate',
            field=models.CharField(default='', max_length=100, verbose_name='المحافظة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/', verbose_name='صورة العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الوحدات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='area_sqm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='المساحة (متر مربع)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='الطابق'),
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإيجار الشهري'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('متاحة', 'متاحة'), ('مؤجرة', 'مؤجرة'), ('الصيانة', 'تحت الصيانة'), ('غير نشطة', 'غير نشطة')], default='متاحة', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('شقة', 'شقة'), ('مكتب', 'مكتب'), ('محل', 'محل تجاري'), ('مخزن', 'مخزن'), ('موقف', 'موقف سيارات'), ('أخرى', 'أخرى')], default='', max_length=20, verbose_name='نوع الوحدة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertycategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='UnitFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='الميزة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.unit')),
            ],
            options={
                'verbose_name': 'ميزة الوحدة',
                'verbose_name_plural': 'مزايا الوحدات',
            },
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='units/images/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit')),
            ],
            options={
                'verbose_name': 'صورة وحدة',
                'verbose_name_plural': 'صور الوحدات',
            },
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
