# Generated by Django 5.0.3 on 2025-04-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertycategory_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='unitfeature',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_units',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='unitimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='المساحة بالمتر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الحمامات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مفروشة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم العقار'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(verbose_name='الطابق'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الإيجار الشهري'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('rented', 'مؤجرة'), ('maintenance', 'صيانة')], default='available', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل تجاري'), ('warehouse', 'مخزن'), ('parking', 'موقف سيارات')], max_length=20, verbose_name='نوع الوحدة'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(upload_to='unit_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit', verbose_name='الوحدة'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='الميزة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.unit', verbose_name='الوحدة')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyCategory',
        ),
        migrations.DeleteModel(
            name='UnitFeature',
        ),
    ]
