# Generated by Django 5.0.2 on 2025-04-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_area_property_created_at_and_more'),
        ('tenants', '0002_remove_tenant_monthly_rent_tenant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='نسبة المالك')),
                ('investor_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='نسبة المستثمر')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('description', models.TextField(max_length=255, verbose_name='الوصف')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='العقار')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ الدخل')),
                ('description', models.TextField(max_length=255, verbose_name='الوصف')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='العقار')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant', verbose_name='المستأجر')),
            ],
        ),
    ]
